//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokdeneme.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesaplar
    {
        public int Hesap_ID { get; set; }
        public string Hesap_Ad { get; set; }
        public Nullable<int> Bloke_Suresi { get; set; }
    }
}
