//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokdeneme.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stokEntities1 : DbContext
    {
        public stokEntities1()
            : base("name=stokEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firmalar> Firmalar { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<KDV> KDV { get; set; }
        public virtual DbSet<Markalar> Markalar { get; set; }
        public virtual DbSet<Odemeler> Odemeler { get; set; }
        public virtual DbSet<Satislar> Satislar { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<Hesaplar> Hesaplar { get; set; }
        public virtual DbSet<Satis_Detay> Satis_Detay { get; set; }
        public virtual DbSet<Siparis_Detay> Siparis_Detay { get; set; }
        public virtual DbSet<Stok> Stok { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
    }
}
