//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokdeneme.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis_Detay
    {
        public int Satis_ID { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public int Urun_ID { get; set; }
        public Nullable<int> Urun_adet { get; set; }
        public Nullable<decimal> Birim_fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
