//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokdeneme.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int Sepet_ID { get; set; }
        public int Urun_ID { get; set; }
        public Nullable<int> Urun_Miktar { get; set; }
        public Nullable<decimal> KDVsiz_fiyat { get; set; }
        public Nullable<decimal> Toplam_fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public int Firma_ID { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<int> KDV_ID { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Firmalar Firmalar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual KDV KDV { get; set; }
    }
}
