//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokdeneme.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparisler()
        {
            this.Siparis_Detay = new HashSet<Siparis_Detay>();
        }
    
        public int Siparis_ID { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public Nullable<decimal> Siparis_Tutar { get; set; }
        public Nullable<decimal> Odenen_Tutar { get; set; }
        public Nullable<System.DateTime> Siparis_Tarih { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis_Detay> Siparis_Detay { get; set; }
    }
}
