//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokdeneme.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Sepet = new HashSet<Sepet>();
            this.Siparis_Detay = new HashSet<Siparis_Detay>();
        }
    
        public int Urun_ID { get; set; }
        public Nullable<int> Barkod_no { get; set; }
        public string Urun_Ad { get; set; }
        public int Marka_ID { get; set; }
        public int Kategori_ID { get; set; }
        public decimal KDV_Haric_Fiyat { get; set; }
        public int KDV_ID { get; set; }
        public decimal Yuzdelik_Kar { get; set; }
        public int Iskonto { get; set; }
        public int Stok { get; set; }
        public int Firma_ID { get; set; }
        public string Resim { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
        public virtual kategoriler kategoriler { get; set; }
        public virtual KDV KDV { get; set; }
        public virtual Markalar Markalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis_Detay> Siparis_Detay { get; set; }
    }
}
